"""Module 14: FastAPI Service.

This module provides the HTTP, REST, and streaming interface boundary
for AI Marketing Studio PRO, exposing robust FastAPI endpoints.
"""

from src.api.exceptions import (
    APIServiceError,
    APIConfigurationError,
    APIInitializationError,
    DependencyResolutionError,
    InvalidAPIRequestError,
    RequestValidationError,
    AuthenticationError,
    MissingCredentialsError,
    InvalidCredentialsError,
    ExpiredCredentialsError,
    AuthorizationError,
    ForbiddenOperationError,
    RateLimitExceededError,
    ResourceNotFoundError,
    ResourceConflictError,
    IdempotencyConflictError,
    InvalidIdempotencyKeyError,
    RequestTimeoutError,
    ServiceUnavailableError,
    DownstreamServiceError,
    ProjectAPIError,
    AssetAPIError,
    WorkflowAPIError,
    WorkflowEventError,
    ProgressStreamError,
    ResponseSerializationError,
    PaginationError,
    MiddlewareError,
    OpenAPIConfigurationError,
    ShutdownError,
)

from src.api.api_models import (
    APIStatus,
    APIErrorCode,
    AuthenticationScheme,
    Permission,
    ResourceType,
    WorkflowEventType,
    ProgressTransportType,
    PaginationMetadata,
    APIErrorDetail,
    APIErrorResponse,
    APISuccessResponse,
    HealthResponse,
    LivenessResponse,
    ReadinessResponse,
    ProjectCreateRequest,
    ProjectOpenRequest,
    ProjectSaveAsRequest,
    ProjectCloseRequest,
    ProjectDeleteRequest,
    ProjectSummaryResponse,
    ProjectDetailResponse,
    ProjectValidationResponse,
    AssetImportRequest,
    ExternalAssetRegistrationRequest,
    AssetDeleteRequest,
    AssetResponse,
    AssetListResponse,
    WorkflowInputReferencesRequest,
    WorkflowOptionsRequest,
    WorkflowStartRequest,
    FullVideoWorkflowRequest,
    ScriptOnlyWorkflowRequest,
    SpeechOnlyWorkflowRequest,
    SubtitleOnlyWorkflowRequest,
    RenderOnlyWorkflowRequest,
    WorkflowResumeRequest,
    WorkflowRetryRequest,
    WorkflowRegenerateStepRequest,
    WorkflowCancelRequest,
    WorkflowInputResponseRequest,
    StepExecutionResultResponse,
    WorkflowProgressResponse,
    ResumeInformationResponse,
    WorkflowOutputReferencesResponse,
    WorkflowResponse,
    WorkflowStateResponse,
    WorkflowEventResponse,
    BatchWorkflowRequest,
    BatchWorkflowResponse,
    SettingsResponse,
    SettingsUpdateRequest,
    ServerInformationResponse,
    DiagnosticsResponse,
    CapabilityResponse,
    SecureServiceCredentials,
    SafePathResponse,
)

from src.api.protocols import (
    LoggerProtocol,
    ClockProtocol,
    IdProviderProtocol,
    IdempotencyStoreProtocol,
    RateLimiterBackendProtocol,
    ProgressBrokerProtocol,
    AuthenticationProviderProtocol,
    AuthorizationProviderProtocol,
)

from src.api.api_config import APIConfig

__all__ = [
    # Exceptions
    "APIServiceError",
    "APIConfigurationError",
    "APIInitializationError",
    "DependencyResolutionError",
    "InvalidAPIRequestError",
    "RequestValidationError",
    "AuthenticationError",
    "MissingCredentialsError",
    "InvalidCredentialsError",
    "ExpiredCredentialsError",
    "AuthorizationError",
    "ForbiddenOperationError",
    "RateLimitExceededError",
    "ResourceNotFoundError",
    "ResourceConflictError",
    "IdempotencyConflictError",
    "InvalidIdempotencyKeyError",
    "RequestTimeoutError",
    "ServiceUnavailableError",
    "DownstreamServiceError",
    "ProjectAPIError",
    "AssetAPIError",
    "WorkflowAPIError",
    "WorkflowEventError",
    "ProgressStreamError",
    "ResponseSerializationError",
    "PaginationError",
    "MiddlewareError",
    "OpenAPIConfigurationError",
    "ShutdownError",
    
    # Models & Enums
    "APIStatus",
    "APIErrorCode",
    "AuthenticationScheme",
    "Permission",
    "ResourceType",
    "WorkflowEventType",
    "ProgressTransportType",
    "PaginationMetadata",
    "APIErrorDetail",
    "APIErrorResponse",
    "APISuccessResponse",
    "HealthResponse",
    "LivenessResponse",
    "ReadinessResponse",
    "ProjectCreateRequest",
    "ProjectOpenRequest",
    "ProjectSaveAsRequest",
    "ProjectCloseRequest",
    "ProjectDeleteRequest",
    "ProjectSummaryResponse",
    "ProjectDetailResponse",
    "ProjectValidationResponse",
    "AssetImportRequest",
    "ExternalAssetRegistrationRequest",
    "AssetDeleteRequest",
    "AssetResponse",
    "AssetListResponse",
    "WorkflowInputReferencesRequest",
    "WorkflowOptionsRequest",
    "WorkflowStartRequest",
    "FullVideoWorkflowRequest",
    "ScriptOnlyWorkflowRequest",
    "SpeechOnlyWorkflowRequest",
    "SubtitleOnlyWorkflowRequest",
    "RenderOnlyWorkflowRequest",
    "WorkflowResumeRequest",
    "WorkflowRetryRequest",
    "WorkflowRegenerateStepRequest",
    "WorkflowCancelRequest",
    "WorkflowInputResponseRequest",
    "StepExecutionResultResponse",
    "WorkflowProgressResponse",
    "ResumeInformationResponse",
    "WorkflowOutputReferencesResponse",
    "WorkflowResponse",
    "WorkflowStateResponse",
    "WorkflowEventResponse",
    "BatchWorkflowRequest",
    "BatchWorkflowResponse",
    "SettingsResponse",
    "SettingsUpdateRequest",
    "ServerInformationResponse",
    "DiagnosticsResponse",
    "CapabilityResponse",
    "SecureServiceCredentials",
    "SafePathResponse",
    
    # Protocols
    "LoggerProtocol",
    "ClockProtocol",
    "IdProviderProtocol",
    "IdempotencyStoreProtocol",
    "RateLimiterBackendProtocol",
    "ProgressBrokerProtocol",
    "AuthenticationProviderProtocol",
    "AuthorizationProviderProtocol",
    
    # Config
    "APIConfig",
]
