"""Stable public API for Module 08: Text-To-Speech (Fish Speech Engine).

This module exposes the unified models, exception hierarchies, and typing contracts
for the AI Marketing Studio PRO TTS service layer.
"""

from src.tts.exceptions import (
    AudioProcessingError,
    CacheError,
    FileOutputError,
    GenerationCancelledError,
    GenerationError,
    GenerationTimeoutError,
    GPUOutOfMemoryError,
    InvalidGeneratedAudioError,
    InvalidRequestError,
    InvalidTextError,
    InvalidVoiceError,
    ModelLoadError,
    ModelNotLoadedError,
    QueueError,
    ReferenceAudioError,
    TTSConfigError,
    TTSEngineError,
    UnsupportedAudioFormatError,
    UnsupportedDeviceError,
    VoiceCloningError,
)
from src.tts.protocols import TTSCache, TTSModelRunner, TTSQueue, VoiceRegistry
from src.tts.tts_models import (
    AudioChannelMode,
    AudioFormat,
    BatchGenerationResult,
    BatchTTSRequest,
    CacheInfo,
    DeviceType,
    GenerationPriority,
    GenerationProgress,
    GenerationResult,
    HealthStatus,
    ModelStatus,
    QueueTaskInfo,
    ReferenceVoiceInfo,
    TaskStatus,
    TTSGenerationSettings,
    TTSPostProcessingSettings,
    TTSRequest,
    VoiceMetadata,
    VoiceType,
)

__all__ = [
    # Custom Exceptions
    "TTSEngineError",
    "TTSConfigError",
    "UnsupportedDeviceError",
    "GPUOutOfMemoryError",
    "ModelLoadError",
    "ModelNotLoadedError",
    "InvalidRequestError",
    "InvalidTextError",
    "InvalidVoiceError",
    "ReferenceAudioError",
    "VoiceCloningError",
    "GenerationError",
    "GenerationTimeoutError",
    "GenerationCancelledError",
    "QueueError",
    "CacheError",
    "AudioProcessingError",
    "InvalidGeneratedAudioError",
    "UnsupportedAudioFormatError",
    "FileOutputError",
    # Enums
    "DeviceType",
    "TaskStatus",
    "VoiceType",
    "AudioChannelMode",
    "AudioFormat",
    "GenerationPriority",
    # Dataclasses
    "ReferenceVoiceInfo",
    "TTSPostProcessingSettings",
    "TTSGenerationSettings",
    "TTSRequest",
    "BatchTTSRequest",
    "VoiceMetadata",
    "GenerationProgress",
    "GenerationResult",
    "BatchGenerationResult",
    "QueueTaskInfo",
    "CacheInfo",
    "ModelStatus",
    "HealthStatus",
    # Protocols
    "TTSModelRunner",
    "VoiceRegistry",
    "TTSCache",
    "TTSQueue",
]
